version: "3.8"
services:
  server:
    build: ./server
    container_name: react_test_server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server
      - /server/node_modules
  client:
    build: ./client
    container_name: react_test_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    stdin_open: true
    tty: true
