version: "3.9"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000
    volumes:
      - ./server:/server
      - /server/node_modules
  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    stdin_open: true
    tty: true
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=react_test_server
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql:/var/lib/mysql/
      - ./db:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=admin
      - PMA_PASSWORD=password
      - PMA_DATABASE=react_test_server
