name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{ secrets.SSH_KEY }}"
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9CAJq7kL83DPIeH4AMWxsYQG5WvVVqqyZj+pTJqHGMbnRwk/i4Rzs1UVEwqfY+mx8xDELOEL4ZgERhFuJlTFJP1smrAq9jTt+WoRv1+2s/t9QM0T2YjDfYIeS1VqL0A/u+ySLIMjBnJPcNhAfon0M5jn4VhRw1u1nV3vdoK0xuiaOBU9vpqD3MUFJjIx1LPZ4qqXZp1xLZGoA/OiL6GYoy1uZbuPRk1Bd354EQJ3lZw/t2SxkDTivnE1lsT4HGBkeBIqk0Ih62oN/mNhVDd0v1RyBnGNtlQGUMyu8csax9Oftf80COHG2EojoiLMgiGcbEamty1mB0l/SvR8desoecHYKPm9V5U/lmWVhlIeeSwvrWkrxx9EmOPfDKnBMSVXIJKyc4qtSKwYkbRyjAstwaiI/0luECrwdTXYrP+W+Bx8cKmgsYpud8IgFZFedtEVz+SNMfL035C0kUr7Hqz8RGvKLsTKyx6sXkSUOu/akbNf1OMjgIMLkCS6rAyDp6ks= alex@hivex.com'
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir test 
            cd test 
            git clone git@github.com/dennisofficial/react-test-project.git 
            echo 'Deployment successful to digital ocean' 
